### ISSUE TITLE
Weight difference showing incorrect values 

### ISSUE THREAD

**Issue by amink4** [Honey-Pi/rpi-scripts#16]
I think the weight difference before/after maintenance mode is not showing correct values. During maintenance mode, I removed approx. 3kg of material/food from the hive, but after finishing maintenance, the field for sum of weight difference shows +11,7kg and -13000%. Before I started the maintenance mode, the value was -0,09 kg.
So I'm not sure how this is supposed to work. 
I'm using version 1.42.
Any help would be highly appreciated.

**Comment by elschnorro77** [comment]
Hi @amink4,
is it possible to attatch the logfile from the measurements in request so we could investigate what went wrong.
It measures the weight when the maintenance mode is started (and is not using last measurement). So it could be the case that you started working on the hive a bit to early. But please let's investigate from the logfile.

**Comment by amink4** [comment]
Sure, I can grab the log tomorrow and will attach it.

**Comment by amink4** [comment]
Attached you find the log.
[honeypi.log](https://github.com/Honey-Pi/rpi-scripts/files/14551233/honeypi.log)

I guess I already found out what the problem was. Before working on the hive, weight was 33kg.
Seems HoneyPi is doing a measurement at the beginning of maintenance mode. It took around 40 sec to get first value from scale and I guess I was already working on the hive. Then the script recognized inconsistent values and retried measurements 6 times and finally took fallback value of 19,9kg. After maintenance mode, the weight is 29kg, so delta is around +9kg. Next time, I will try to wait 2 or 3 minutes after starting maintenance mode. But wouldn't it be a better solution to simply pick the last value that was measured before starting maintenance mode? This would avoid that someone is already working on the hive while a new measurement takes place. Or maybe this could be a option in the UI so that it can be configured if a new measurement should be taken or not. What do you think?
